
include $(USER_DEPTH)/make/makeinclude/mk_pre.mak

USER_LIB = dipcvnetutils

USER_SRCS_CPP= \
dipcvnetutils.cpp\
DIPCVNetType.cpp\
CMacTable.cpp\
MACAddress.cpp\
CWhiteList.cpp\
CBlackList.cpp\
DIPCVNetPolicyType.cpp

USER_INCLDIRS =\
-I$(USER_DEPTH)/src/\
-I$(USER_DEPTH)/src/main/\
-I$(USER_DEPTH)/src/dipcvnet/\
-I$(USER_DEPTH)/src/include/\
-I$(USER_DEPTH)/src/dipcvos/\
-I$(USER_DEPTH)/src/utils\
-I$(USER_DEPTH)/src/vswitch
USER_DEFFLAGS =
USER_LINK_LIBS =
USER_LINK_DLLS =
USER_LINK_FLAGS=



USER_OBJ_DIR=$(TARGET_PATH)/src/dipcvnetutils

include $(USER_DEPTH)/make/makeinclude/mk_post.mak



