
include $(USER_DEPTH)/make/makeinclude/mk_pre.mak

USER_LIB = vnet

USER_SRCS_CPP= \
CDIPCVnetManager.cpp\
CDIPCVnetTap.cpp\
\
CDIPCVnetSwitchPort.cpp\
CDIPCVnetSwitchPortLocal.cpp\
CDIPCVnetSwitchManager.cpp

USER_INCLDIRS =\
-I$(USER_DEPTH)/src/\
-I$(USER_DEPTH)/src/vnet/\
-I$(USER_DEPTH)/src/dipcvnet

USER_DEFFLAGS =
USER_LINK_LIBS =
USER_LINK_DLLS =
USER_LINK_FLAGS=



USER_OBJ_DIR=$(TARGET_PATH)/src/vnet

include $(USER_DEPTH)/make/makeinclude/mk_post.mak



